version: "3.9"

services:
  coder:
    image: ghcr.io/coder/coder:latest
    ports:
      - "7080:7080"
    environment:
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "coder.${BASE_DOMAIN}"
    env_file:
      - .coder.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres-coder

  postgres-coder:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .coder.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro


networks:
  traefik:
    external: true