version: "3.9"

services:
  coder:
    image: ghcr.io/coder/coder:latest
    environment:
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "https://coder.${BASE_DOMAIN}"
    env_file:
      - .coder.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres-coder
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coder.rule=Host(`coder.${BASE_DOMAIN}`)"
      - "traefik.http.routers.coder.entrypoints=websecure"
      - "traefik.http.routers.coder.tls=true"
      - "traefik.http.routers.coder.tls.certresolver=cloudflare"
      - "traefik.http.services.coder.loadbalancer.server.port=7080"

  postgres-coder:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .coder.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=false"


networks:
  traefik:
    external: true